image: Visual Studio 2017

for:
-
  matrix:
    only:
      - image: Visual Studio 2015
  build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH="C:\\Qt\\5.11.3\\msvc2015\\"
  - cmake --build .
-
  matrix:
    only:
      - image: Visual Studio 2017
  build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH="C:\\Qt\\5.12.2\\msvc2017\\"
  - cmake --build .
